### ISSUE TITLE
Unable to create new Circuit

### ISSUE THREAD

**Issue by RememberNelson** [fallinbryan/FNA#11]
**Describe the bug**
I am unable to create a new circuit ID becuase the operation is not valid due to the current state of the object.

**To Reproduce**
1. Go to 'Sites. Then Create a Network element. Then you create a new slot. Once you create a new port click on the fiber identification and decribe your fiber. '
2. Now sta yon that same screen and click create new circuit. 
3. Then type in "Cspire2017"

**Expected behavior**
i expected not to get an error when i submitted a curcuit ID with letters and integers.

**Comment by fallinbryan** [comment]
unable to reproduce error
